### ISSUE TITLE
Use constant for playerAName

### ISSUE THREAD

**Issue by DobbysGamertag** [realdiegopoptart/samp-libaries#1]
No need for magic numbers. 

Use MAX_PLAYER_NAME. 

https://github.com/realdiegopoptart/iafk/blob/main/iafk.inc#L13

**Comment by realdiegopoptart** [comment]
Yeah, I probably should've done that

I should also do a check if ysi included else use forloops.

**Comment by realdiegopoptart** [comment]
Merged.
